// topics
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_REQ = 'FETCH_TOPICS_REQ';
export const CHANGE_ISFETCHING_STATE = 'CHANGE_ISFETCHING_STATE';
export const CLEAR_STATE_DATA = 'CLEAR_STATE_DATA';
