// topics
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_SUBJECT = 'FETCH_TOPICS_SUBJECT';
export const FETCH_TOPICS_REQ = 'FETCH_TOPICS_REQ';
export const CHANGE_ISFETCHING_STATE = 'CHANGE_ISFETCHING_STATE';
export const CLEAR_STATE_DATA = 'CLEAR_STATE_DATA';

// user
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const LOGOUT = 'LOGOUT';
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE';
