// topics
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_SUBJECT = 'FETCH_TOPICS_SUBJECT';
export const FETCH_TOPICS_REQ = 'FETCH_TOPICS_REQ';
export const CHANGE_ISFETCHING_STATE = 'CHANGE_ISFETCHING_STATE';
export const CLEAR_STATE_DATA = 'CLEAR_STATE_DATA';

// user
export const FETCH_USER = 'FETCH_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const LOGOUT = 'LOGOUT';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE';

// usertopics
export const GET_LIST_DATA = 'GET_LIST_DATA';
export const CLEAR_LIST_DATA = 'CLEAR_LIST_DATA';

// commentaries
export const STATE_SHOW_COMMDETAILS = 'STATE_SHOW_COMMDETAILS';
export const COLLECT_TOPIC = 'COLLECT_TOPIC';
export const DEL_COLLECTED_TOPIC = 'DEL_COLLECTED_TOPIC';

// message
export const GET_MESSAGE_COUNT = 'GET_MESSAGE_COUNT';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CLEAR_MESSAGE_DATA = 'CLEAR_MESSAGE_DATA';
